home:
  a_su_servicio: "ul.tb-megamenu-nav li:nth-child(3) a.dropdown-toggle"
  reclamos_tile: "div.sutel_shortcut_container a[href*='/sutel/reclamos/formulario']"
  aresep_lnk: "a[href='http://www.aresep.go.cr']"
