home:
  a_su_servicio: "ul.tb-megamenu-nav li:nth-child(3) a.dropdown-toggle"
  reclamos_tile: "div.sutel_shortcut_container a[href*='/sutel/reclamos/formulario']"
  micit_lnk: "a[href='http://www.micit.go.cr']"
  search_txt: "edit-search-block-form--2"
  search_btn: "edit-submit"
  facebook_btn: "#block-block-4 a[href*='facebook']"
  avisos: ".sutel_shortcut_container a[href*='avisos']"
  fonatel: "ul.tb-megamenu-nav li:nth-child(5) a.dropdown-toggle"
