prepaid:
  register_number_btn: "botonAceptar"
  continue_btn: "botonContinuar"
  accept_terms_btn: "botonAceptar"
  costarricense_rdo: "idRadioCosta"
  number_txt: "idNumeroPrepagoCosta"
  add_number_btn: "idAnadirCosta"
  email_txt: "idCorreoCosta"
  id_owner_txt: "idNumCeldaTitularCosta"
  code_txt: "idCodigoImpresoCosta"
  submit_btn: "enviarCosta"
  error_msg: "div.bootbox-body"
